gentoo_mirror: http://distfiles.gentoo.org
#gentoo_mirror: https://mirror.yandex.ru/gentoo-distfiles
repository: /var/lib/gentoo-build

#repository_domain: gentoo.somedomain.com
repository_overlays: [ kvaster ]

ruby: ruby30

groups:
  amd64:
    - generic
    - zen2
    - core2
    - broadwell
    - sandybridge
    - skylake
    - goldmontplus
  arm64:
    - rpi
    - rpi4

chost_amd64: &chost_amd64
  chost: x86_64-pc-linux-gnu
  os_arch: amd64
  profile: default/linux/amd64/17.1
  pkgs_stage4: pkgs_stage4_amd64
  pkgs_all: pkgs_all_amd64
  kernel: "5.12"
  initramfs: true
  kernel_build_pkgs:
    - app-arch/zstd

chost_arm64: &chost_arm64
  chost: aarch64-unknown-linux-gnu
  os_arch: arm64
  qemu: qemu-aarch64
  profile: default/linux/arm64/17.0
  pkgs_stage4: pkgs_stage4_arm64
  pkgs_all: pkgs_all_arm64
  kernel: "5.12"
  kernel_dtbs: true
  kernel_build_pkgs:
    - app-arch/zstd

archs:
  broadwell:
    <<: *chost_amd64
    cflags: -O3 -pipe -march=broadwell -mtune=broadwell -mabm -mrtm -maes
    x86flags: aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3
    kernel_config: MBROADWELL
  core2:
    <<: *chost_amd64
    cflags: -O3 -pipe -march=core2 -mtune=core2
    x86flags: mmx mmxext sse sse2 sse3 ssse3
    kernel_config: MCORE2
  generic:
    <<: *chost_amd64
    cflags: -O3 -pipe
    x86flags: ''
    kernel_config: GENERIC_CPU
  sandybridge:
    <<: *chost_amd64
    cflags: -O3 -pipe -march=sandybridge -mtune=sandybridge
    x86flags: aes avx mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3
    kernel_config: MSANDYBRIDGE
  skylake:
    <<: *chost_amd64
    cflags: -O3 -pipe -march=skylake -mtune=skylake -mabm
    x86flags: aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3
    kernel_config: MSKYLAKE
  zen2:
    <<: *chost_amd64
    cflags: -O3 -pipe -march=znver2 -mtune=znver2
    x86flags: aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3
    kernel_config: MZEN2
  goldmontplus:
    <<: *chost_amd64
    cflags: -O3 -pipe -march=goldmont-plus -mtune=goldmont-plus
    x86flags: aes mmx mmxext pclmul popcnt sha sse sse2 sse3 sse4_1 sse4_2 ssse3
    kernel_config: MGOLDMONTPLUS
  rpi:
    <<: *chost_arm64
    cflags: -O3 -pipe -march=armv8-a+crc+simd -mtune=cortex-a53
  rpi4:
    <<: *chost_arm64
    cflags: -O3 -pipe -march=armv8-a+crc+simd -mtune=cortex-a72

pkgs_stage4_common: &pkgs_stage4_common
  - app-admin/metalog
  - app-admin/sudo
  - app-admin/logrotate
  - app-arch/p7zip
  - app-editors/nano
  - app-editors/vim
  - app-misc/mc
  - app-misc/tmux
  - app-portage/gentoolkit
  - dev-lang/ruby
  - net-firewall/iptables
  - net-firewall/nftables
  - net-misc/ntp
  - net-wireless/bluez
  - net-wireless/iw
  - net-wireless/wpa_supplicant
  - sys-apps/gptfdisk
  - sys-apps/iproute2
  - sys-apps/pciutils
  - sys-apps/usbutils
  - sys-fs/btrfs-progs
  - sys-fs/compsize
  - sys-fs/dosfstools
  - sys-kernel/linux-firmware
  - sys-power/acpi
  - sys-power/acpid
  - sys-process/cronie

pkgs_stage4_arm64: &pkgs_stage4_arm64
  - *pkgs_stage4_common
  - dev-embedded/rpi-eeprom

pkgs_stage4_amd64: &pkgs_stage4_amd64
  - *pkgs_stage4_common
  - sys-apps/ipmitool
  - sys-boot/grub
  - sys-firmware/intel-microcode
  - sys-fs/mdadm
  - sys-kernel/genkernel

pkgs_all_common: &pkgs_all_common
  - *pkgs_stage4_common
  - app-metrics/nut_exporter
  - app-portage/layman
  - dev-db/postgresql
  - net-analyzer/tcpdump
  - net-analyzer/traceroute
  - net-libs/nodejs
  - net-misc/dhcpcd
  - net-vpn/wireguard-tools
  - sys-apps/ethtool
  - sys-apps/yarn
  - www-servers/nginx

pkgs_all_arm64: &pkgs_all_arm64
  - *pkgs_all_common
  - *pkgs_stage4_arm64
  - dev-util/ccache

pkgs_all_amd64: &pkgs_all_amd64
  - *pkgs_all_common
  - *pkgs_stage4_amd64
  - app-admin/helm
  - app-arch/pixz
  - app-crypt/certbot
  - app-crypt/certbot-dns-rfc2136
  - app-emulation/cri-tools
  - app-emulation/containerd
  - app-metrics/alertmanager
  - app-metrics/node_exporter
  - app-metrics/prometheus
  - app-portage/cpuid2cpuflags
  - app-portage/smart-live-rebuild
  - dev-db/mongodb
  - dev-java/nexus-oss-bin
  - dev-java/openjdk:8
  - dev-java/openjdk:11
  - dev-java/openjdk:14
  - dev-java/openjdk:15
  - dev-java/openjdk-bin:8
  - dev-java/openjdk-bin:11
  - dev-java/openjdk-bin:14
  - dev-java/openjdk-bin:15
  - dev-vcs/mercurial
  - dev-vcs/subversion
  - mail-mta/exim
  - net-firewall/conntrack-tools
  - net-firewall/ipset
  - net-misc/miniupnpd
  - net-misc/socat
  - net-dns/bind-tools
  - net-dns/knot
  - net-dns/knot-resolver
  - net-nds/openldap
  - net-misc/netkit-telnetd
  - sys-apps/dbus
  - sys-cluster/kubeadm
  - sys-cluster/kubelet
  - sys-cluster/kubectl
  - sys-cluster/keepalived
  - sys-cluster/lizardfs
  - sys-libs/freeipmi
